### PR TITLE
Installing Husky and setting up prepush task

### PR DESCRIPTION
**Pull request by sergiohpreis**
I installed Husky on dependencies and configured the prepush task :)

### CODE REVIEW

**Comment by willianjusten** [comment]
Exactly what I said =)
But just thinking here, it should check if after the `build` our code is different. Because now, I still can push without the updated code. Because of the following order:

- I tried to do a push
- It runs the `build` and there are changes in the new
- But I pushed anyway, because my hook just wants to run the build, not add it.

**Comment by willianjusten** [comment]
I'll accept and do a small change here, let's see =)

**Comment by willianjusten** [comment]
Meh, I tried adding `npm run build && git add . && git commit --amend --no-edit`, but I don't know why, it pushes the old "commit" even the new is amended. I'll check more lately.

But it's okay for now, since this site is managed by me and I know what to do lol

**Comment by sergiohpreis** [comment]
Nice :), I'll check it later too :)

**Pull request merged**
